### ISSUE TITLE
Anilist metadata incorrectly pulling in metadata

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#19]
For anime series on anilist that has a 4 digits or less, the metadata agent is correctly grabbing links to the related page, as the number of digits increase the accuracy is off (Either 404 or incorrect link)

Examples:
Code Geass: Lelouch of the Rebellion Links to https://anilist.co/anime/1575 which is correct
Darling in the Franxx Links to http://anilist.co/anime/35849/ Which is incorrect and leads to a 404, it should link to https://anilist.co/anime/99423

The following error message may or may not be related (It did bring this problem to my attention)
```
[23:44:26] [ERR] Error in AniList
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Jellyfin.Plugin.Anime.Providers.AniList.Api.WebRequestAPI(String link)
   at Jellyfin.Plugin.Anime.Providers.AniList.AniListSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by hawken93** [comment]
I was about to blame short ints because 99423 - 65535 = 33888 but that's also off.. I continue suspect this is some internal datatype messup

**Comment by hawken93** [comment]
Must be something here setting it wrong.. Possible to add debug statement and see what it sets?

https://github.com/jellyfin/jellyfin-plugin-anime/blob/6e53511e9275e9da2d00cc419d4c4cab79718dbd/MediaBrowser.Plugins.Anime/Providers/AniList/api.cs#L334

**Comment by hawken93** [comment]
Medium defines it as 32 bits here https://github.com/jellyfin/jellyfin-plugin-anime/blob/6e53511e9275e9da2d00cc419d4c4cab79718dbd/MediaBrowser.Plugins.Anime/Providers/AniList/ApiModel.cs#L40

**Comment by hawken93** [comment]
Deserialized here https://github.com/jellyfin/jellyfin-plugin-anime/blob/6e53511e9275e9da2d00cc419d4c4cab79718dbd/MediaBrowser.Plugins.Anime/Providers/AniList/api.cs#L380

**Comment by anthonylavado** [comment]
The issue is that the search on AniList is trying to use the same ID that the anime has on MAL

I don’t know why this is the case, but that’s what appears to be happening.

For example, the Code Geass show is here on MyAnimeList: https://myanimelist.net/anime/1575/

The ID is 1575, which matches the ID that AniList has.

For Darling in the Franxx, MyAnimeList has it here: https://myanimelist.net/anime/35849

The ID is 35849, which as you mentioned, is the wrong one for AniList.

**Comment by anthonylavado** [comment]
Also, 1575 is the correct ID for CG: LotR on both MAL sand AniList.

**Comment by Matt07211** [comment]
As @cvium mentioned in matrix chat

AniList can use the MAL ID to search.

https://anilist.github.io/ApiV2-GraphQL-Docs/media.doc.html

**Comment by cvium** [comment]
It's broken by this change here: https://github.com/jellyfin/jellyfin-plugin-anime/blob/f3df278b2559d710a48f4cd75fe32b037bbb6b7a/Jellyfin.Plugin.Anime/Providers/AniDB/Metadata/AniDbSeriesProvider.cs#L369-L370

`firstId` is a MAL id, so I suggest re-adding the providername (not the provider itself) and use the id as an extra parameter for the anilist query if it's present. Example query:

```graphql
https://graphql.anilist.co/api/v2?query=
query ($query: String, $idMal: Int, $type: MediaType) {
  Page {
    media(search: $query, idMal: $idMal, type: $type) {
      id
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
        large
      }
      format
      type
      averageScore
      popularity
      episodes
      season
      hashtag
      isAdult
      startDate {
        year
        month
        day
      }
      endDate {
        year
        month
        day
      }
    }
  }
}&variables={ "query":"Darling in the Franxx","idMal":"35849", "type":"ANIME"}
```

Another example with just the idMal:
```graphql
https://graphql.anilist.co/api/v2?query=query($idMal: Int, $type: MediaType) {
  Media(idMal: $idMal, type: $type)
        {
            id
            title {
                romaji
                english
              native
      userPreferred
            }
            startDate {
                year
                month
              day
            }
            endDate {
                year
                month
              day
            }
            coverImage {
                large
                medium
            }
            bannerImage
            format
    type
    status
    episodes
    chapters
    volumes
    season
    description
    averageScore
    meanScore
    genres
    synonyms
    nextAiringEpisode {
                airingAt
                timeUntilAiring
      episode
    }
        }
    }&variables={ "idMal":"35849","type":"ANIME"}
```
