### ISSUE TITLE
Use MalID for more accurate search on AniList

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#22]
During the discussion of https://github.com/jellyfin/jellyfin-plugin-anime/issues/19 it was found that you can use MalId: 1234 to find a better more accurate search on AniList. 

I am creating this new issue as the previous issue was for incorrect IDs being used, wheres this can be considered a feature/enhancement, as well as to create open discussion on this idea (If it is smart or not to implement)

**Comment by dkanada** [comment]
Closing this since we no longer use MyAnimeList as a provider.
