### ISSUE TITLE
Configuration page not displaying entries (JS error) w/latest Jellyfin master + 2.0.0

### ISSUE THREAD

**Issue by lbeltrame** [jellyfin/jellyfin-plugin-anime#36]
I updated Jellyfin from the latest master state, removed the existing anime plugin, then installed it from the catalog. 

The configuration page is constantly spinning without doing anything:

![Screenshot_20190428_154334](https://user-images.githubusercontent.com/25192/56865271-6594b480-69cc-11e9-944c-1f272bba0b53.png)

In the JS console of Firefox, I see, when accessing the plugin configuration page:

```
Error: null Id                                                                                              apiclientcore.js:823:24
    getPluginConfiguration https://example.com/web/bower_components/apiclient/apiclientcore.js?v=10.3.1:823
    loadConfiguration https://example.com/web/index.html#!/configurationpage?name=Anime line 38 > scriptElement:12
    <anonymous> https://example.com/web/index.html#!/configurationpage?name=Anime line 38 > scriptElement:45
    jQuery 2
    onViewChange https://example.com/web/components/viewManager/viewManager.js?v=10.3.1:65
    loadView https://example.com/web/components/viewManager/viewManager.js?v=10.3.1:151
```

**Comment by lbeltrame** [comment]
I made sure I also cleaned the pre-existing configuration and the issue seems to persist.

EDIT: Forgot to mention, the Jellyfin installation is accessed through a reverse proxy.

**Comment by lbeltrame** [comment]
Actually, I think it's a red herring, because you can actually set things in the client, and they get even saved, but they won't get loaded once you get back to the page (same sympthom).

**Comment by Matt07211** [comment]
What does the configuration get saved as?

I've had the configuration page be real finicky in the past, I think at one point I had to restart the server to read the configuration. But that was a few months back.

Also is it broken on the latest jellyfin release or only latest jellyfin master?

**Comment by lbeltrame** [comment]
I'll paste what I found, in the `<jellyfin data dir>/plugins/configurations`. I just ignored the spinner and put the data in (the forms weren't disabled).

```xml

<?xml version="1.0"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">                                                 
  <TitlePreference>Localized</TitlePreference>
  <TidyGenreList>true</TidyGenreList>
  <MaxGenres>0</MaxGenres>
  <AddAnimeGenre>true</AddAnimeGenre>
  <UseAnidbOrderingWithSeasons>true</UseAnidbOrderingWithSeasons>
  <AniDB_wait_time>5000</AniDB_wait_time>
</PluginConfiguration
```

The file is saved as Jellyfin.Plugin.Anime.xml.
The way I set it up makes it difficult to test with a release.

**Comment by Matt07211** [comment]
Is the missing > human error or is that actually missing from the configuration? Also is the config named the same as the dll?

**Comment by lbeltrame** [comment]
The > missing is a copy-paste error. As for the DLL and the configuration: same names.

**Comment by Matt07211** [comment]
Well we can rule one thing out, I'll see about getting an instance up and see if I can reproduce it.

**Comment by StillLoading** [comment]
Just noticed that there have been some updates. Got the same error after upgrading (clean plugin install).

This seems to be the culprit.

https://github.com/jellyfin/jellyfin-plugin-anime/blob/13b8305f885d7b711df09bbde02519c64e231593/Jellyfin.Plugin.Anime/Configuration/configPage.html#L64

It should be: AnimeConfigurationPage.pluginUniqueId 

I'll push a PR in a sec.

Edit: PR is online. I'm not really setup for testing right now so I had to test on my live installation and as far as I can tell it works again.
