### ISSUE TITLE
AniDB Wait Time

### ISSUE THREAD

**Issue by XVicarious** [jellyfin/jellyfin-plugin-anime#5]
As someone who has been dealing with AniDB, I highly suggest setting the default wait time to at least 2500ms. They're really strict on their rate limits set in 2005.

**Comment by Matt07211** [comment]
Per Anidb docs

> server enforces a strict flood protection policy.
> 
> Short Term:
> A Client MUST NOT send more than 0.5 packets per second (that's one packet every two seconds, not two packets a second!)
> The server will start to enforce the limit after the first 5 packets have been received.
> Long Term:
> A Client MUST NOT send more than one packet every four seconds over an extended amount of time.
> An extended amount of time is not defined. Use common sense.

And by default I think the plugin is set at 0 (and is user configurable), so for a proper fix we should adhere to the rules but for the moment you can just set the time limit yourself

**Comment by hawken93** [comment]
They mean requests per second right? Tcp connection establishment breaks this alone..

**Comment by Matt07211** [comment]
If I hazourd a guess without looking at the code I'd say the plugin is using the UDP API. As the http API is considered limit in their docs, and the TCP API is considered private.

https://wiki.anidb.net/w/API#Core_Services
