### ISSUE TITLE
AniDB uses backtick/grave in metadata

### ISSUE THREAD

**Issue by JustAPerson** [jellyfin/jellyfin-plugin-anime#61]
It seems AniDB always uses a backtick/grave character (U+0060 `GRAVE ACCENT`) as an apostrophe in their official titles. I'm not sure what other metadata attributes are affected. In English speaking countries, it's standard to use a single quote (U+0027 `APOSTROPHE`) instead.

Could a simple text replacement be performed here? Perhaps any grave directly before or after an `s` character could be replaced with a proper apostrophe.

Feel free to close if this is out of scope. I came across https://github.com/jellyfin/jellyfin-web/issues/997 because of this behavior. Had stuff like this in my catalog
![2020-03-28_08:48:08_250x438](https://user-images.githubusercontent.com/789308/77823361-02763b00-70d1-11ea-977e-7359ad694cf8.png)

**Comment by dkanada** [comment]
I've always hated the grave characters from AniDB, here's a [pull request](https://github.com/jellyfin/jellyfin-plugin-anime/pull/62) to optionally replace them.
