### ISSUE TITLE
MyAnimeList API is dead

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#7]
MyAnimeList API has been down for  a long while, and there is no word when it will be available again, I suggest dropping MyAnimeList from the plugin till such time that they make the API public again, at which point we would need to rewrite the code for the new API anyways.

**Comment by anthonylavado** [comment]
I’ve read up on the MAL issue, and I say go ahead with this. There is an unofficial API in Jikan, but it would need a new implementation as well if we were to support it.

Ref: https://github.com/jikan-me/jikan/blob/master/readme.md

**Comment by Matt07211** [comment]
Yeah, I made mention of that particular project in the jellyfin-dev chat, but in my personal opinion, scraping html for a small time project with a small amount of users is fine, but for the size of jellyfin I don't think it is appropriate, plus it feels like a grey area.

If and when the API does become public again we can add back the support
