### ISSUE TITLE
Split metadata providers to separate plugins

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin-plugin-anime#82]
Splitting the different metadata providers to different plugins would allow;

Pros
------
 - Choosing which providers to install
 - Separately manage issues
 - Subscribing to issues about only the metadata managers you care about
 - Updating providers separately

Cons
------
 - More plugin repos to manage
 - More work releasing plugins until CI is set up

**Comment by StillLoading** [comment]
There was a [topic](https://forum.jellyfin.org/t/shall-we-split-the-anime-and-channel-repo-contents-into-individual-repos/49) in the forums about this a long time ago, but it's been stale ever since.

**Comment by senritsu** [comment]
On topic of CI, how exactly are jellyfin plugins built&deployed?

**Comment by crobibero** [comment]
> 
> 
> On topic of CI, how exactly are jellyfin plugins built&deployed?

We have a webhook that runs https://github.com/oddstr13/jellyfin-plugin-repository-manager to build & deploy the plugin

**Comment by oddstr13** [comment]
Specifically, a slightly modified version of this script is used to call the jprm program in the deploy pipelines;
https://github.com/oddstr13/jellyfin-plugin-repository-manager/blob/master/build_plugin.sh
This is also the script I use locally to build and test plugins.

---

I'm aware that this issue has been brought up on multiple occasions before, and was painfully reminded of it when I started updating plugins for the 10.7 cycle.

**Comment by oddstr13** [comment]
- https://github.com/jellyfin/jellyfin-plugin-anilist
- https://github.com/jellyfin/jellyfin-plugin-anidb
- https://github.com/jellyfin/jellyfin-plugin-anisearch
- https://github.com/jellyfin/jellyfin-plugin-kitsu

It has been done :tada:
