### ISSUE TITLE
Remove German as a Title Language Option 

### ISSUE THREAD

**Issue by Matt07211** [jellyfin/jellyfin-plugin-anime#9]
Currently the plugin has 2 metadata providers that pulls in data that is German (Proxer and AniSearch), but neither of those sites offer a German version of the name, due to this, the function of having German as a Title option is completely useless. Removing it as an option seems the most straight forward.

**Comment by hawken93** [comment]
When thinking about this some more, all libraries lets you set the preferred metadata language. Instead of asking the user in the plugin configuration, maybe this plugin could consult the library language to decide which language it should get
